[tool.poetry]
name = "portfolio"
version = "0.1.0"
description = ""
authors = ["skow0020"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.2"
flask = "^2.2.3"
gunicorn = "20.1.0"
pytest = "^7.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
